In [1]:
import pandas as pd
import numpy as np

from sklearn import preprocessing

# Feature Scaling
### Min-Max Normalization
- new = (original-min)/(max-min)
### Standardization

### 1st practice

In [5]:
NBA_FILE_PATH = "C:/_SY/alone_practice/codeit/ml/NBA_player_of_the_week.csv"
nba_player_of_the_week_df = pd.read_csv(NBA_FILE_PATH)

In [6]:
nba_player_of_the_week_df.describe()

Weight          Age   Draft Year  Seasons in league  Season short  \
count  1340.000000  1340.000000  1340.000000        1340.000000   1340.000000   
mean    224.567164    26.738060  1996.287313           5.740299   2003.156716   
std      30.798885     3.400683    11.253558           3.293421     11.470164   
min     150.000000    19.000000  1965.000000           0.000000   1980.000000   
25%     205.000000    24.000000  1987.000000           3.000000   1994.000000   
50%     220.000000    26.000000  1998.000000           5.000000   2005.000000   
75%     250.000000    29.000000  2005.000000           8.000000   2013.000000   
max     325.000000    40.000000  2018.000000          17.000000   2020.000000   

        Real_value    Height CM    Weight KG  Last Season  
count  1340.000000  1340.000000  1340.000000  1340.000000  
mean      0.686940   201.071642   101.384328     0.023881  
std       0.242007     9.367970    14.011226     0.152734  
min       0.500000   175.000000    68.000000     0.000000  
25%       0.500000   193.000000    93.000000     0.000000  
50%       0.500000   201.000000    99.000000     0.000000  
75%       1.000000   208.000000   113.000000     0.000000  
max       1.000000   229.000000   147.000000     1.000000

In [7]:
height_weight_age_df = nba_player_of_the_week_df[['Height CM', 'Weight KG', 'Age']]
height_weight_age_df.head()

Height CM  Weight KG  Age
0        203         94   21
1        213        113   25
2        201         99   23
3        190         88   29
4        206        104   25

In [18]:
scaler1 = preprocessing.MinMaxScaler() # Min-Max Normalization : min=0, max=1
normalized_data = scaler1.fit_transform(height_weight_age_df)

scaler2 = preprocessing.StandardScaler() # Standardization : m=0, sigma=1
standarized_data = scaler2.fit_transform(height_weight_age_df)

print(normalized_data)
standarized_data

[[0.51851852 0.32911392 0.0952381 ]
 [0.7037037  0.56962025 0.28571429]
 [0.48148148 0.39240506 0.19047619]
 ...
 [0.48148148 0.37974684 0.23809524]
 [0.38888889 0.21518987 0.23809524]
 [0.42592593 0.27848101 0.52380952]]


array([[ 0.20592274, -0.52722617, -1.68795564],
       [ 1.27378837,  0.82933556, -0.51128218],
       [-0.00765038, -0.17023624, -1.09961891],
       ...,
       [-0.00765038, -0.24163423, -0.80545055],
       [-0.54158319, -1.16980804, -0.80545055],
       [-0.32801007, -0.81281811,  0.95955965]])

In [21]:
normalized_df = pd.DataFrame(normalized_data, columns=['Height', 'Weight', 'Age'])
standarized_df = pd.DataFrame(standarized_data, columns=['Height', 'Weight', 'Age'])

In [22]:
normalized_df.describe()

Height        Weight           Age
count  1.340000e+03  1.340000e+03  1.340000e+03
mean  -7.423581e-16 -4.295072e-16 -3.499688e-16
std    1.000373e+00  1.000373e+00  1.000373e+00
min   -2.784101e+00 -2.383574e+00 -2.276292e+00
25%   -8.619429e-01 -5.986242e-01 -8.054505e-01
50%   -7.650381e-03 -1.702362e-01 -2.171138e-01
75%    7.398556e-01  8.293356e-01  6.653913e-01
max    2.982373e+00  3.256867e+00  3.901243e+00

In [23]:
standarized_df.describe()

Height        Weight           Age
count  1.340000e+03  1.340000e+03  1.340000e+03
mean  -7.423581e-16 -4.295072e-16 -3.499688e-16
std    1.000373e+00  1.000373e+00  1.000373e+00
min   -2.784101e+00 -2.383574e+00 -2.276292e+00
25%   -8.619429e-01 -5.986242e-01 -8.054505e-01
50%   -7.650381e-03 -1.702362e-01 -2.171138e-01
75%    7.398556e-01  8.293356e-01  6.653913e-01
max    2.982373e+00  3.256867e+00  3.901243e+00

### 2nd practice

In [ ]:
PATIENT_FILE_PATH = './datasets/liver_patient_data.csv'
pd.set_option('display.float_format', lambda x: '%.5f' % x)

In [ ]:
# 데이터 DataFrame으로 받아오기
liver_patients_df = pd.read_csv(PATIENT_FILE_PATH)
lliver_patients_df.columns